---
- hosts: 172.31.89.79
  become: yes
  tasks: 
     - include_tasks: myfilehandle.yml

     - name: i want to install apache2
       apt: 
        name: apache2
        state: present


     - name: i want to copy file or create file in node
       template: 
          src: myindex.j2
          dest: /var/www/html/index.html
          