--- 
- name: give the tomcat group ownership
  file:
   path: /opt/tomcat
   state: directory
   recurse: yes
   owner: tomcat
   group: tomcat



- name: give the tomcat group read access to the conf directory and all of its contents
  file: 
  path: /opt/tomcat/conf
  recurse: yes
  mode: g+r
  state: directory


- name: and execute access to the directory itself
  file: 
  path: /opt/tomcat/conf
  mode: g+x
  state: directory


- name: change file ownership of webapps
  file:
    path: /opt/tomcat/webapps
    recurse: yes
    owner: tomcat
    state: directory


- name: change file ownership of work
  file:
    path: /opt/tomcat/work
    recurse: yes
    owner: tomcat
    state: present

- name: change file ownership of temp 
  file: 
    path: /opt/tomcat/temp
    recurse: yes
    owner: tomcat
    state: present

- name: change file ownership of logs 
  file: 
    path: /opt/tomcat/logs
    recurse: yes
    owner: tomcat
    state: present
    